# WhatATheme
livereload: true
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Frenzied Marmot
# Description of the Site
description: Making games, game-related apps, and game dev content
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: games, game development, programming, web development, developer
# URL for the Image of custom Favicon
favicon-url: /assets/images/favicon.ico

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/background.jpg
heroinnerimage: /assets/images/birds.png

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: aaron.moore@frenziedmarmot.com
facebook_username: frenziedmarmot
twitter_username: frenziedmarmot
instagram_username: 
linkedin_username: 
github_username:  frenziedmarmot
youtube_channel_id: UCeQ3S4Ite1MBL8R27UzeXSw
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: 

# Name of the Author
author-name: FrenziedMarmot
# URL for the Image of the Author
author-image: /assets/images/logo.png
author-image-sm: /assets/images/logo-sm.png
# 60 Words About the Author
author-about: We are an indie game development studio with the aim of having fun making fun games. We've released 2 titles for mobile platforms with a secret project in the works. We also build/host websites. Frenzied Marmot is based in Arkansas, United States.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/frenziedmarmot

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
